name: app_movil
description: Aplicación móvil para gestión de inventario de equipos informáticos en Canvia.
version: 1.0.0+1  # Versión (semver) + build number

environment:
  sdk: '>=3.7.0 <4.0.0'  # Compatibilidad con Dart/Flutter
  flutter: '>=3.19.0'     # Versión mínima de Flutter

dependencies:
  flutter:
    sdk: flutter
  # Dependencias principales
  provider: ^6.1.1        # Gestión de estado (MVC)
  http: ^1.1.0            # Consumo de APIs REST
  shared_preferences: ^2.2.2  # Almacenamiento local
  intl: ^0.18.1           # Formateo de fechas/números
  pdf: ^3.10.2            # Generación de reportes (opcional)
  syncfusion_flutter_datagrid: ^23.1.40  # Tablas dinámicas (opcional)
  qr_code_scanner: ^1.0.1
  flutter_barcode_scanner: ^2.0.0 # o la versión más reciente  #AGREGADO PARA QR
  qr_flutter: ^4.1.0 #AGREGADO PARA QR

dev_dependencies:
  flutter_test:
    sdk: flutter          # Para pruebas widget
  flutter_lints: ^3.0.0   # Análisis de código
  mockito: ^5.4.0         # Para pruebas unitarias (opcional)

flutter:
  uses-material-design: true
  assets:
#    - assets/images/      # Ruta para imágenes (opcional)

